# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BadgeSystem' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "TextFieldEffects"
  pod 'Alamofire', '~> 4.0'
  pod 'IrohaSwift','~> 1.0.0a5'
  pod 'PMAlertController'
  pod 'KeychainAccess'
  # Pods for BadgeSystem

  target 'BadgeSystemTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BadgeSystemUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
